version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.8.0

    working_directory: ~/scheduler

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test

  deploy:
    machine:
      enabled: true

    working_directory: ~/.

    steps:
      - add_ssh_keys:
          fingerprints:
            - "e0:b0:72:18:5c:f4:0e:ca:87:30:8c:7e:89:8c:a7:fa"
      - checkout
      - run:
          name: Push Master to Production
          command: |
            git push https://github.com/senayson/scheduler.git master:production

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - build:
          filters:
            branches:
              ignore: production
      - deploy:
          filters:
            branches:
              ignore: production
          requires:
            - build
